### ISSUE TITLE
:not(:contains()) shows 'CSS selector is not well formed.'

### ISSUE THREAD

**Issue by magicdice** [technosophos/querypath#172]
When i try to retrieve data with :not(:contains()), it shows 'CSS selector is not well formed.'
Did i missed something??
Here is my code :
```
<?php
require_once 'vendor/autoload.php';

$html=<<<HTML
<ul class="ul_sc" >
  <li class="lis" title="0">
    <span class="pid">PC146622</span>
    <span class="msg">sold</span>
  </li>
  <li class="lis" title="2">
    <span class="pid">PC146623</span>
    <span class="msg"></span>
  </li>
  <li class="lis" title="4">
    <span class="pid">PC146624</span>
    <span class="msg">sold</span>
  </li>
</ul>
HTML;

$qp = qp($html, null, array(
    'convert_from_encoding'  => 'UTF-8',
    'convert_to_encoding'    => 'UTF-8',
    'ignore_parser_warnings' => true,
  )
);

$result = $qp->find('ul.ul_sc li.lis:not(:contains(sold))');
foreach ( $result as $item) {
  echo $item->attr('title') . "\n";
}
```
Result:
```
PHP Fatal error:  Uncaught exception 'QueryPath\CSS\ParseException' with message 'CSS selector is not well formed.' in ./vendor/querypath/querypath/src/QueryPath/CSS/Parser.php:71
Stack trace:
#0 ./vendor/querypath/querypath/src/QueryPath/CSS/DOMTraverser.php(123): QueryPath\CSS\Parser->parse()
#1 ./vendor/querypath/querypath/src/QueryPath/DOMQuery.php(276): QueryPath\CSS\DOMTraverser->find('ul.ul_sc li.lis...')
#2 ./scripts/test.php(29): QueryPath\DOMQuery->find('ul.ul_sc li.lis...')
#3 {main}
  thrown in ./vendor/querypath/querypath/src/QueryPath/CSS/Parser.php on line 71

Fatal error: Uncaught exception 'QueryPath\CSS\ParseException' with message 'CSS selector is not well formed.' in ./vendor/querypath/querypath/src/QueryPath/CSS/Parser.php on line 71

QueryPath\CSS\ParseException: CSS selector is not well formed. in ./vendor/querypath/querypath/src/QueryPath/CSS/Parser.php on line 71

Call Stack:
    0.0004     231168   1. {main}() ./scripts/test.php:0
    0.0465    1489880   2. QueryPath\DOMQuery->find() ./scripts/test.php:29
    0.0509    1704928   3. QueryPath\CSS\DOMTraverser->find() ./vendor/querypath/querypath/src/QueryPath/DOMQuery.php:276
    0.0623    1943144   4. QueryPath\CSS\Parser->parse() ./vendor/querypath/querypath/src/QueryPath/CSS/DOMTraverser.php:123
```

**Comment by technosophos** [comment]
I believe it is the case that in CSS3, you can't use pseudo-classes inside of a `:not()`.

You'll probably want to do something like `$qp->find('ul.ul_sc li.lis')` and then use `->not()`, `->filter()` or one of the other filtering functions.

**Comment by magicdice** [comment]
Thanks for reply.

Your suggestion does works, but I just wondering the selector I wrote works while i made a test using jQuery. [jsFiddle](http://jsfiddle.net/MagicDice/0ead185y/10/)

And I also checked the spec of [The negation pseudo-class](http://www.w3.org/TR/selectors/#negation)
, it shows that the negation pseudo-class works with other pseudo-classes, like 

```
html|*:not(:link):not(:visited)
```
Plz correct me, if i misunderstood anything. Thanks.

**Comment by technosophos** [comment]
You are right. Only child selectors are disallowed inside of the `:not()` pseudo-class. The `:contains()` pseudo-class was removed from the spec, so I probably didn't implement it very carefully. http://www.w3.org/TR/css3-selectors/#content-selectors

If jQuery supports it, then this is a bug. I'll work on it.

**Comment by magicdice** [comment]
Thank you so much, just can't wait to see that.
